name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["ContiGPT"]
assignees:
  - miguelangelorebelo
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see. Provide error messages if applicable.
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: model
    attributes:
      label: model
      description: What llm model did you select?
      options:
        - "databricks/dolly-v2-3b"
        - "databricks/dolly-v2-7b"
        - "Open-Orca/Mistral-7B-OpenOrca"
      default: 0
    validations:
      required: true
  - type: dropdown
    id: task
    attributes:
      label: Where was the model running?
      multiple: true
      options:
        - "Cloud"
        - "Local (Windows)"
        - "Local Ubuntu"
        - "Local Mac"
